/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Grupo;
import model.Relatorio;

/**
 *
 * @author conta
 */
public final class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    
    private String grupoSelecionado;
    private List<Object[]> listaPublicadores = new ArrayList<>();
    private List<Relatorio> tabelaRelatorio = new ArrayList<>();
   
    /**
     * Creates new form Teste
     */
    public TelaPrincipal() {
        initComponents();
        
        //Paineil Relatório
        informarMesAtual();
        entregarAte();
        contadorDias();
        habilitarCaixa();
        
        //Painel Grupos
        
        atualizarTabelaGrupos();
        atualizarQuantidadePublicadores();
        tblGrupos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {

                int linha = tblGrupos.getSelectedRow();
                
                if (linha == -1) return;
                if (Grupo.listarGrupos().isEmpty()) return;
                if (linha >= Grupo.listarGrupos().size()) return;
                
                // Define o grupo ativo
                grupoSelecionado = tblGrupos.getValueAt(linha, 0).toString();

                atualizarQuantidadePublicadores();
                atualizarTabelaPublicadores();
                atualizarNumeroGrupo();
            }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlRelatorio = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMesAtual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDataEntrega = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        pnlRelatar = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbtSim = new javax.swing.JRadioButton();
        rbtNao = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxModalidade = new javax.swing.JComboBox<>();
        txtHoras = new javax.swing.JTextField();
        txtEstudos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pnlGrupos = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblNumeroGrupo = new javax.swing.JLabel();
        lblQuantidadePublicadores = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btnRemoverPublicador = new javax.swing.JButton();
        btnAdicionarPublicador = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblGrupos = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPublicadores = new javax.swing.JTable();
        btnCriarGrupo = new javax.swing.JButton();
        btnExcluirGrupo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArquivo = new javax.swing.JMenu();
        mniJwHub = new javax.swing.JMenuItem();
        mniVisualizar = new javax.swing.JMenuItem();
        mniSalvar = new javax.swing.JMenuItem();
        mnConfiguracoes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mês de Serviço:");

        lblMesAtual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMesAtual.setText("[mês]");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Entregar até:");

        lblDataEntrega.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDataEntrega.setText("[data]");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Praso:");

        lblContador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContador.setText("[dias]");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMesAtual)
                    .addComponent(jLabel1))
                .addGap(185, 185, 185)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(lblDataEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblContador)
                    .addComponent(jLabel14))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(lblContador))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(lblDataEntrega))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(lblMesAtual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Faltam Entregar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Ir");

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Publicadores - Qunatidade", null},
                {"Publicadores - Relatando", null},
                {"Publicadores - Estudos", null},
                {"Pioneiro Auxiliar - Quantidade", null},
                {"Pioneiro Auxiliar - Estudos", null},
                {"Pioneiro Regular - Quantidade", null},
                {"Pioneiro Regular - Estudos", null},
                {"Total de Estudos", null},
                {null, null}
            },
            new String [] {
                "Modalidade", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("Salvar no Excel");

        javax.swing.GroupLayout pnlRelatorioLayout = new javax.swing.GroupLayout(pnlRelatorio);
        pnlRelatorio.setLayout(pnlRelatorioLayout);
        pnlRelatorioLayout.setHorizontalGroup(
            pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRelatorioLayout.createSequentialGroup()
                        .addGroup(pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRelatorioLayout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlRelatorioLayout.setVerticalGroup(
            pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relatório", new javax.swing.ImageIcon(getClass().getResource("/icons/relatorio.png")), pnlRelatorio); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Perquisar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("[Nome do publicador]");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Publicador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatar"));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Participou da pregação este mês:");

        rbtSim.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtSim.setText("Sim");

        rbtNao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtNao.setText("Não");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Modalidade:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Horas:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Estudos:");

        cbxModalidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxModalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Publicador", "Pioneiro Auxiliar", "Pioneiro Regular", "Pioneiro Especial" }));

        txtHoras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtEstudos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEstudos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstudosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(rbtSim)
                        .addGap(29, 29, 29)
                        .addComponent(rbtNao))
                    .addComponent(cbxModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEstudos, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtSim)
                    .addComponent(rbtNao)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstudos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRelatarLayout = new javax.swing.GroupLayout(pnlRelatar);
        pnlRelatar.setLayout(pnlRelatarLayout);
        pnlRelatarLayout.setHorizontalGroup(
            pnlRelatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRelatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlRelatarLayout.createSequentialGroup()
                        .addGroup(pnlRelatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRelatarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );
        pnlRelatarLayout.setVerticalGroup(
            pnlRelatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRelatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addGroup(pnlRelatarLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatar", new javax.swing.ImageIcon(getClass().getResource("/icons/publicador.png")), pnlRelatar); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        lblNumeroGrupo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroGrupo.setText("Grupo 0");

        lblQuantidadePublicadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantidadePublicadores.setText("Pessoas");

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setText("Pesquisar");

        btnRemoverPublicador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRemoverPublicador.setText("Remover");
        btnRemoverPublicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPublicadorActionPerformed(evt);
            }
        });

        btnAdicionarPublicador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdicionarPublicador.setText("Adicionar");
        btnAdicionarPublicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPublicadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblNumeroGrupo)
                    .addComponent(lblQuantidadePublicadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarPublicador)
                .addGap(4, 4, 4)
                .addComponent(btnRemoverPublicador)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lblNumeroGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadePublicadores))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(btnRemoverPublicador)
                            .addComponent(btnAdicionarPublicador))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblGrupos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblGrupos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGrupos.setRowHeight(30);
        tblGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGruposMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblGrupos);
        if (tblGrupos.getColumnModel().getColumnCount() > 0) {
            tblGrupos.getColumnModel().getColumn(0).setResizable(false);
        }

        tblPublicadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblPublicadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Modalidade", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPublicadores.setRowHeight(30);
        jScrollPane5.setViewportView(tblPublicadores);
        if (tblPublicadores.getColumnModel().getColumnCount() > 0) {
            tblPublicadores.getColumnModel().getColumn(0).setResizable(false);
        }

        btnCriarGrupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCriarGrupo.setText("Criar Grupo");
        btnCriarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarGrupoActionPerformed(evt);
            }
        });

        btnExcluirGrupo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluirGrupo.setText("Excluir Grupo");
        btnExcluirGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGruposLayout = new javax.swing.GroupLayout(pnlGrupos);
        pnlGrupos.setLayout(pnlGruposLayout);
        pnlGruposLayout.setHorizontalGroup(
            pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlGruposLayout.createSequentialGroup()
                        .addGroup(pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCriarGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluirGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        pnlGruposLayout.setVerticalGroup(
            pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGruposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlGruposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGroup(pnlGruposLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCriarGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirGrupo)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Grupos", new javax.swing.ImageIcon(getClass().getResource("/icons/grupos.png")), pnlGrupos); // NOI18N

        mnArquivo.setText("Arquivo");

        mniJwHub.setText("Abrir JW Hub");
        mnArquivo.add(mniJwHub);

        mniVisualizar.setText("Visualizar");
        mniVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarActionPerformed(evt);
            }
        });
        mnArquivo.add(mniVisualizar);

        mniSalvar.setText("Salvar");
        mnArquivo.add(mniSalvar);

        jMenuBar1.add(mnArquivo);

        mnConfiguracoes.setText("Configurações");

        jMenuItem2.setText("Alterar data da entrega");
        mnConfiguracoes.add(jMenuItem2);
        mnConfiguracoes.add(jSeparator1);

        jMenuItem5.setText("Tamanho do texto");
        mnConfiguracoes.add(jMenuItem5);

        jMenuBar1.add(mnConfiguracoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if (!rbtSim.isSelected() && !rbtNao.isSelected()) {
            JOptionPane.showMessageDialog(null, "Imforme se o publicadou participou em alguma modalidade este mês");
            return;
        }
        if (
                cbxModalidade.getSelectedItem()=="Pioneiro Auxiliar" ||
                cbxModalidade.getSelectedItem()=="Pioneiro Rgular") {
            txtHoras.setEnabled(true);
            txtEstudos.setEnabled(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtEstudosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstudosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstudosActionPerformed

    private void mniVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniVisualizarActionPerformed

    private void btnCriarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarGrupoActionPerformed
        Grupo g = new Grupo();
        
        // exemplo: número automático
        g.setNumeroGrupo(Grupo.listarGrupos().size() + 1);
        
        // Cria o grupo
        g.criarGrupo();
        
        //Atualiza a tabela
        atualizarTabelaGrupos();
    }//GEN-LAST:event_btnCriarGrupoActionPerformed

    private void btnExcluirGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirGrupoActionPerformed
        int linhaSelecionada = tblGrupos.getSelectedRow();
        
        if (linhaSelecionada != -1) {
            Grupo g = Grupo.listarGrupos().get(linhaSelecionada);
            g.excluirGrupo();
            atualizarTabelaGrupos();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um grupo para remover.");
        }     
    }//GEN-LAST:event_btnExcluirGrupoActionPerformed

    private void btnAdicionarPublicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPublicadorActionPerformed
        PublicadorVIEW tela = new PublicadorVIEW(this, grupoSelecionado);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionarPublicadorActionPerformed

    private void btnRemoverPublicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPublicadorActionPerformed
        int linhaGrupo = tblGrupos.getSelectedRow();
        int linhaPublicador = tblPublicadores.getSelectedRow();

        if (linhaGrupo == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um grupo.");
            return;
        }

        if (linhaPublicador == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um publicador.");
            return;
        }

        Grupo g = Grupo.listarGrupos().get(linhaGrupo);

        g.removerPublicador(linhaPublicador);

        atualizarTabelaPublicadores();
        atualizarQuantidadePublicadores();
    }//GEN-LAST:event_btnRemoverPublicadorActionPerformed

    private void tblGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGruposMouseClicked
        int linha = tblGrupos.getSelectedRow();
        
        grupoSelecionado = tblGrupos.getValueAt(linha, 0).toString();
        
        atualizarTabelaPublicadores();
    }//GEN-LAST:event_tblGruposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPublicador;
    private javax.swing.JButton btnCriarGrupo;
    private javax.swing.JButton btnExcluirGrupo;
    private javax.swing.JButton btnRemoverPublicador;
    private javax.swing.JComboBox<String> cbxModalidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblContador;
    private javax.swing.JLabel lblDataEntrega;
    private javax.swing.JLabel lblMesAtual;
    private javax.swing.JLabel lblNumeroGrupo;
    private javax.swing.JLabel lblQuantidadePublicadores;
    private javax.swing.JMenu mnArquivo;
    private javax.swing.JMenu mnConfiguracoes;
    private javax.swing.JMenuItem mniJwHub;
    private javax.swing.JMenuItem mniSalvar;
    private javax.swing.JMenuItem mniVisualizar;
    private javax.swing.JPanel pnlGrupos;
    private javax.swing.JPanel pnlRelatar;
    private javax.swing.JPanel pnlRelatorio;
    private javax.swing.JRadioButton rbtNao;
    private javax.swing.JRadioButton rbtSim;
    private javax.swing.JTable tblGrupos;
    private javax.swing.JTable tblPublicadores;
    private javax.swing.JTextField txtEstudos;
    private javax.swing.JTextField txtHoras;
    // End of variables declaration//GEN-END:variables
    
    /**
     * RELATÓRIO
     */
    private String informarMesAtual() {
        LocalDate hoje = LocalDate.now();
        String mes = hoje.getMonth()
                .getDisplayName(TextStyle.FULL, new Locale("pt","BR"))
                .toUpperCase();
        lblMesAtual.setText(mes);
        lblMesAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        return mes;
    }
    
    private void contadorDias() {
        LocalDate hoje = LocalDate.now();
        
        int diaAtual = hoje.getDayOfMonth();
        
        int diaLimite = 20; //Futuramente poderár ser alterado pelo usuário na aba configuração
        
        if (diaAtual<=diaLimite) {
            int diasRestantes = diaLimite - diaAtual;
            lblContador.setText(diasRestantes + " DIAS");
            lblContador.setForeground(Color.green);
        } else {
            lblContador.setForeground(Color.red);
            lblContador.setText("FECHADO");
            lblContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); //Texto aparecer no centro
            //mudarCorPainelContador();
        }
    }
    
    public void entregarAte() {
        String dia = "20 de "; //Futuramente este valor deve ser passado por parâmetro
        String mes = informarMesAtual();
        lblDataEntrega.setText(dia + mes);
    }
    
    /**
     * RELATAR
     */
    public void habilitarCaixa() {
        String escolha = cbxModalidade.getSelectedItem().toString();
        if (escolha.contains("Pioneiro")) {
            txtHoras.setEnabled(true);
            txtEstudos.setEnabled(true);
        } else {
            txtHoras.setEnabled(false);
            txtEstudos.setEnabled(false);
        }
    }
    
    public void atualizarTabelaConsolidada() {

        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);

        for (Object[] p : listaPublicadores) {
            model.addRow(new Object[]{
                p[0], // nome
            });
        }
    }
    
    public void atualizarTabelaRelatorio() {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        for (Relatorio r : tabelaRelatorio) {
            model.addRow(new Object[]{
                r.getNomePublicador(),
                r.getGrupo(),
            });
        }
    }
    
    /**
     * GRUPOS
     */
    private void atualizarTabelaGrupos() {
        DefaultTableModel model = (DefaultTableModel) tblGrupos.getModel();
        model.setRowCount(0); //Limpa a tabela
        
        for (Grupo g : Grupo.listarGrupos()) {
            model.addRow(new Object[]{
                "Grupo " + g.getNumeroGrupo()
                //g.getPublicadores.size() - implementar mais tarde
            });
        }
    }
    
    private void atualizarTabelaPublicadores() {
        
        if (grupoSelecionado == null) return;
        
        DefaultTableModel model = (DefaultTableModel) tblPublicadores.getModel();
        model.setRowCount(0); //Limpa a tabela
        
        for (Object[] p : listaPublicadores) {
            if (p[3].equals(grupoSelecionado)) {
                model.addRow(new Object[]{
                p[0], //nome
                p[1], //modalidade
                p[2]  //ativo
                }); 
            }    
        }
    }
    
    private void atualizarQuantidadePublicadores() {
        int linha = tblGrupos.getSelectedRow();
        
        if (linha != -1) {
            Grupo g = Grupo.listarGrupos().get(linha);
            int quantidade = g.getPublicadores().size();
            
            lblQuantidadePublicadores.setText(quantidade + " Pessoas");
        } else {
            lblQuantidadePublicadores.setText("0 Pessoas");
        }
    }
    
    public void atualizarNumeroGrupo() {
        int numero = tblGrupos.getSelectedRow();
        if (numero != -1) {
            Grupo g = Grupo.getListaGrupos().get(numero);
            String strNumero = String.valueOf(numero+1);
            lblNumeroGrupo.setText("Grupo " + strNumero);
        } else {
            lblNumeroGrupo.setText("Grupo 0");
        }
    }
    
    public void adicionarNaTabela(String nomePublicador, String modalidade, String ativo, String grupo) {
        listaPublicadores.add(new Object[]{
            nomePublicador,
            modalidade,
            ativo,
            grupo});
        
        atualizarTabelaPublicadores();
    }
    
    public List<String> getListaGrupos() {
        List<String> grupos = new ArrayList<>();
        
        DefaultTableModel model = (DefaultTableModel) tblGrupos.getModel();
        
        for (int i = 0; i < model.getRowCount(); i++) {
            grupos.add(model.getValueAt(i, 0).toString());
        }
        return grupos;
    }
    
    public void buscarPublicador() {
        
        if (grupoSelecionado == null) {
            JOptionPane.showMessageDialog(null, "Selecione um grupo primeiro");
            return;
        }
        
        String busca = jTextField4.getText().toLowerCase();
        
        if (busca.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe um nome para buscar");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblPublicadores.getModel();
        
        boolean encontrado = false;
        
        for (int i = 0; i < model.getRowCount(); i++) {
            String nome = model.getValueAt(i, 0).toString().toLowerCase();
            
            if (nome.contains(busca)) {
                
                tblPublicadores.setRowSelectionInterval(i, i); // Selecina a linha
                tblPublicadores.scrollRectToVisible(
                        tblPublicadores.getCellRect(i, 0, true)); // Rola a tebela até lá
                encontrado = true;
                break;
            }
        }
        
        if (!encontrado) {
            JOptionPane.showMessageDialog(null, "Publicador não encontrado neste grupo");
        }
    }
}
